---
editor: source
---


```{r, warning=FALSE, message=FALSE}

library(dplyr)
library(readr)
library(googlesheets4)
library(here)
library(tidyr)
library(stringr)
library(tibble)
library(DatawRappr)

i_am("dropped_runs.qmd")

```


```{r}

publish_to_dw <- TRUE

ss <- "1OxsU3-A1oFJ0Ay4nPu76VSkX3HT13S35A3BUT3XCF5k"

months <- c(month.name[7:12], month.name[1:6])

all_months <- tibble::tibble()

for (m in months) {
  
  month_data <- read_sheet(ss, sheet = m) %>%
      janitor::clean_names() %>%
      mutate(month = m,) %>%
      mutate(
        date_click_twice_for_calendar = as.character(date_click_twice_for_calendar),
        route_affected = as.character(route_affected),
        run_affected_24hr_format = as.character(run_affected_24hr_format),
        driver = as.character(driver),
        bus = as.character(bus),
        reason = as.character(reason),
        reason_detail = as.character(reason_detail),
        notes = as.character(notes)
      )

  all_months <- bind_rows(all_months, month_data)
  
}

```


```{r}

dropped_runs_chrt_dta <- all_months %>%
  mutate(
    reason_str = paste0(reason, " - ", reason_detail),
    year = if_else(month %in% month.name[7:12], 2025L, 2026L),
    month_start = as.Date(
      paste("1", month, year),
      format = "%d %B %Y"
    )
  ) %>%
  count(month_start, reason) %>%
  pivot_wider(names_from = "month_start", values_from = "n")

# write.csv(dropped_runs_chrt_dta, stdout(), row.names = FALSE)

dw_chart_id <- "uLNyj"
if (publish_to_dw) {
  dw_data_to_chart(dropped_runs_chrt_dta, dw_chart_id, parse_dates = FALSE)
  dw_publish_chart(dw_chart_id, return_urls = FALSE) 
}

```


